export const VelhonTaloudenhoitajaPages: string[] = [
  "s1.png",
  "s2.png",
  "s3.png",
  "s4.png",
  "s5.png",
  "s6.png",
  "s7.png",
  "s8.png",
  "s9.png",
  "s10.png",
  "s11.png",
  "s12.png",
  "s13.png",
  "s14.png",
  "s15.png",
  "s16.png",
  "s17.png",
  "s18.png",
  "s19.png",
  "s20.png",
  "s21.png",
  "s22.png",
  "s23.png",
  "s24.png",
  "s25.png",
  "s26.png",
  "s27.png",
  "s28.png",
  "s29.png",
  "s30.png",
  "s31.png",
  "s32.png",
  "s33.png",
  "s34.png",
  "s35.png",
  "s36.png",
  "s37.png",
  "s38.png",
  "s39.png",
  "s40.png",
  "s41.png",
  "s42.png",
  "s43.png",
  "s44.png",
];

export const SiivetonLepakkoPages: string[][] = [
  ["etusivu.png", "question", "answer"],
  ["s1.png", "question", "answer"],
  ["s2.png", "question", "answer"],
  ["s3.png", "question", "answer"],
  ["s4.png", "question", "answer"],
  ["s5.png", "question", "answer"],
  ["s6.png", "question", "answer"],
  ["s7.png", "question", "answer"],
  ["s8.png", "question", "answer"],
  ["s9.png", "question", "answer"],
  ["s10.png", "question", "answer"],
  ["s11.png", "question", "answer"],
  ["s12.png", "question", "answer"],
];

export const VelhonTaloudenhoitajaPagesWithQuestions: string[][] = [
  ["s1.png", "question", "answer"],
  ["s2.png", "question", "answer"],
  ["s3.png", "question", "answer"],
  ["s4.png", "question", "answer"],
  ["s5.png", "question", "answer"],
  ["s6.png", "question", "answer"],
  ["s7.png", "question", "answer"],
  ["s8.png", "question", "answer"],
  ["s9.png", "question", "answer"],
  ["s10.png", "question", "answer"],
  ["s11.png", "question", "answer"],
  ["s12.png", "question", "answer"],
  ["s13.png", "question", "answer"],
  ["s14.png", "question", "answer"],
  ["s15.png", "question", "answer"],
  ["s16.png", "question", "answer"],
  ["s17.png", "question", "answer"],
  ["s18.png", "question", "answer"],
  ["s19.png", "question", "answer"],
  ["s20.png", "question", "answer"],
  ["s21.png", "question", "answer"],
  ["s22.png", "question", "answer"],
  ["s23.png", "question", "answer"],
  ["s24.png", "question", "answer"],
  ["s25.png", "question", "answer"],
  ["s26.png", "question", "answer"],
  ["s27.png", "question", "answer"],
  ["s28.png", "question", "answer"],
  ["s29.png", "question", "answer"],
  ["s30.png", "question", "answer"],
  ["s31.png", "question", "answer"],
  ["s32.png", "question", "answer"],
  ["s33.png", "question", "answer"],
  ["s34.png", "question", "answer"],
  ["s35.png", "question", "answer"],
  ["s36.png", "question", "answer"],
  ["s37.png", "question", "answer"],
  ["s38.png", "question", "answer"],
  ["s39.png", "question", "answer"],
  ["s40.png", "question", "answer"],
  ["s41.png", "question", "answer"],
  ["s42.png", "question", "answer"],
  ["s43.png", "question", "answer"],
  ["s44.png", "question", "answer"],
];
