export const VelhonTaloudenhoitajaPages: string[] = [
  "s1.png",
  "s2.png",
  "s3.png",
  "s4.png",
  "s5.png",
  "s6.png",
  "s7.png",
  "s8.png",
  "s9.png",
  "s10.png",
  "s11.png",
  "s12.png",
  "s13.png",
  "s14.png",
  "s15.png",
  "s16.png",
  "s17.png",
  "s18.png",
  "s19.png",
  "s20.png",
  "s21.png",
  "s22.png",
  "s23.png",
  "s24.png",
  "s25.png",
  "s26.png",
  "s27.png",
  "s28.png",
  "s29.png",
  "s30.png",
  "s31.png",
  "s32.png",
  "s33.png",
  "s34.png",
  "s35.png",
  "s36.png",
  "s37.png",
  "s38.png",
  "s39.png",
  "s40.png",
  "s41.png",
  "s42.png",
  "s43.png",
  "s44.png",
];

export const SiivetonLepakkoPages: string[][] = [
  ["luonnos-etusivu.png", "question", "answer"],
  ["lepakko-s1.png", "question", "answer"],
  ["lepakko-s2.png", "question", "answer"],
  ["lepakko-s3.png", "question", "answer"],
  ["lepakko-s4.png", "question", "answer"],
  ["lepakko-s5.png", "question", "answer"],
  ["lepakko-s6.png", "question", "answer"],
  ["lepakko-s7.png", "question", "answer"],
  ["lepakko-s8.png", "question", "answer"],
  ["lepakko-s9.png", "question", "answer"],
  ["lepakko-s10.png", "question", "answer"],
  ["lepakko-s11.png", "question", "answer"],
  ["lepakko-s12.png", "question", "answer"],
];

export const VelhonTaloudenhoitajaPagesWithQuestions: string[][] = [
  ["velhontaloudenhoitaja-etusivu.png", "question", "answer"],
  ["velhontaloudenhoitaja-s1.png", "question", "answer"],
  ["velhontaloudenhoitaja-s2.png", "question", "answer"],
  ["velhontaloudenhoitaja-s3.png", "question", "answer"],
  ["velhontaloudenhoitaja-s4.png", "question", "answer"],
  ["velhontaloudenhoitaja-s5.png", "question", "answer"],
  ["velhontaloudenhoitaja-s6.png", "question", "answer"],
  ["velhontaloudenhoitaja-s7.png", "question", "answer"],
  ["velhontaloudenhoitaja-s8.png", "question", "answer"],
  ["velhontaloudenhoitaja-s9.png", "question", "answer"],
  ["velhontaloudenhoitaja-s10.png", "question", "answer"],
  ["velhontaloudenhoitaja-s11.png", "question", "answer"],
  ["velhontaloudenhoitaja-s12.png", "question", "answer"],
  ["velhontaloudenhoitaja-s13.png", "question", "answer"],
  ["velhontaloudenhoitaja-s14.png", "question", "answer"],
  ["velhontaloudenhoitaja-s15.png", "question", "answer"],
  ["velhontaloudenhoitaja-s16.png", "question", "answer"],
  ["velhontaloudenhoitaja-s17.png", "question", "answer"],
  ["velhontaloudenhoitaja-s18.png", "question", "answer"],
  ["velhontaloudenhoitaja-s19.png", "question", "answer"],
  ["velhontaloudenhoitaja-s20.png", "question", "answer"],
  ["velhontaloudenhoitaja-s21.png", "question", "answer"],
  ["velhontaloudenhoitaja-s22.png", "question", "answer"],
  ["velhontaloudenhoitaja-s23.png", "question", "answer"],
  ["velhontaloudenhoitaja-s24.png", "question", "answer"],
  ["velhontaloudenhoitaja-s25.png", "question", "answer"],
  ["velhontaloudenhoitaja-s26.png", "question", "answer"],
  ["velhontaloudenhoitaja-s27.png", "question", "answer"],
  ["velhontaloudenhoitaja-s28.png", "question", "answer"],
  ["velhontaloudenhoitaja-s29.png", "question", "answer"],
  ["velhontaloudenhoitaja-s30.png", "question", "answer"],
  ["velhontaloudenhoitaja-s31.png", "question", "answer"],
  ["velhontaloudenhoitaja-s32.png", "question", "answer"],
  ["velhontaloudenhoitaja-s33.png", "question", "answer"],
  ["velhontaloudenhoitaja-s34.png", "question", "answer"],
  ["velhontaloudenhoitaja-s35.png", "question", "answer"],
  ["velhontaloudenhoitaja-s36.png", "question", "answer"],
  ["velhontaloudenhoitaja-s37.png", "question", "answer"],
  ["velhontaloudenhoitaja-s38.png", "question", "answer"],
  ["velhontaloudenhoitaja-s39.png", "question", "answer"],
  ["velhontaloudenhoitaja-s40.png", "question", "answer"],
  ["velhontaloudenhoitaja-s41.png", "question", "answer"],
  ["velhontaloudenhoitaja-s42.png", "question", "answer"],
  ["velhontaloudenhoitaja-s43.png", "question", "answer"],
  ["velhontaloudenhoitaja-s44.png", "question", "answer"],
];
